server:
  port: 4055

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

enableSwagger: ${ENABLE_SWAGGER:true}

config:
  stacktraceEnabled:  ${STACKTRACE_ENABLED:false}

#logging:
#  level:
#    org.springframework: debug

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: wa standalone task bpmn
  main:
    allow-bean-definition-overriding: true

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/v2/api-docs"
