server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

config:
  enableSwagger: ${ENABLE_SWAGGER:true}

spring:
  application:
    name: Wa standalone task bpmn

springdoc:
  writer-with-order-by-keys: true
